create extension if not exists pgcrypto;

create table public.classes (
  id integer generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.streams (
  id integer generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.class_streams (
  id integer generated by default as identity primary key,
  class_id integer not null references public.classes(id) on delete cascade,
  stream_id integer not null references public.streams(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (class_id, stream_id)
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  class_stream_id integer not null references public.class_streams(id) on delete restrict,
  boarding boolean not null default false,
  role text not null default 'student'
    check (role in ('student', 'teacher', 'admin')),
  status text not null default 'active'
    check (status in ('active', 'disabled', 'archived')),
  created_at timestamptz not null default now()
);

create table public.email_messages (
  id uuid primary key default gen_random_uuid(),
  gmail_message_id text not null unique,
  gmail_thread_id text,
  recipient_email text,
  assigned_user_id uuid not null references public.profiles(id) on delete restrict,
  from_email text,
  from_name text,
  subject text,
  snippet text,
  received_at timestamptz not null,
  has_attachments boolean not null default false,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index class_streams_class_id_idx
  on public.class_streams (class_id);

create index class_streams_stream_id_idx
  on public.class_streams (stream_id);

create index profiles_class_stream_id_idx
  on public.profiles (class_stream_id);

create index profiles_status_idx
  on public.profiles (status);

create index email_messages_assigned_user_id_idx
  on public.email_messages (assigned_user_id);

create index email_messages_received_at_idx
  on public.email_messages (received_at desc);

alter table public.classes enable row level security;
alter table public.streams enable row level security;
alter table public.class_streams enable row level security;
alter table public.profiles enable row level security;
alter table public.email_messages enable row level security;

create policy "Authenticated users can view classes"
  on public.classes
  for select
  to authenticated
  using (true);

create policy "Authenticated users can view streams"
  on public.streams
  for select
  to authenticated
  using (true);

create policy "Authenticated users can view class streams"
  on public.class_streams
  for select
  to authenticated
  using (true);

create policy "Users can view their own profile"
  on public.profiles
  for select
  to authenticated
  using (id = auth.uid());

create policy "Users can update their own profile"
  on public.profiles
  for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

create policy "Users can view their assigned messages"
  on public.email_messages
  for select
  to authenticated
  using (assigned_user_id = auth.uid());

create policy "Users can update read state on their assigned messages"
  on public.email_messages
  for update
  to authenticated
  using (assigned_user_id = auth.uid())
  with check (assigned_user_id = auth.uid());

revoke all on public.classes from anon, authenticated;
revoke all on public.streams from anon, authenticated;
revoke all on public.class_streams from anon, authenticated;
revoke all on public.profiles from anon, authenticated;
revoke all on public.email_messages from anon, authenticated;

grant select on public.classes to authenticated;
grant select on public.streams to authenticated;
grant select on public.class_streams to authenticated;

grant select on public.profiles to authenticated;
grant update (full_name, class_stream_id, boarding) on public.profiles to authenticated;

grant select on public.email_messages to authenticated;
grant update (is_read) on public.email_messages to authenticated;

grant all on public.classes to service_role;
grant all on public.streams to service_role;
grant all on public.class_streams to service_role;
grant all on public.profiles to service_role;
grant all on public.email_messages to service_role;
